FROM --platform=${BUILDPLATFORM} golang:1.22.7-alpine3.20 AS whatap_cadvisor_helper_build
#build platform linux/arm64
ARG BUILDPLATFORM
ARG BUILDARCH
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

RUN echo "Kubernetes Cadvisor Helper Build is running on $BUILDPLATFORM, building for $TARGETPLATFORM"

WORKDIR /data/agent/node
COPY . .
RUN if [ "$BUILDARCH" = "amd64" ] && [ "$TARGETARCH" = "amd64" ] ; then cd whatap_sidecar && go mod tidy && CGO_ENABLED=1 GOOS=$TARGETOS GOARCH=$TARGETARCH go build --ldflags='-w -extldflags "-static"' -o /build/result/whatap_sidecar /build/whatap_sidecar/whatap_sidecar.go ; fi
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags='-w -extldflags -static' -tags netgo -tags pluginsenabled -o cadvisor_helper cadvisor_helper.go

RUN ls /data/agent/node
#FROM --platform=${TARGETPLATFORM} alpine as packaging
#
#ARG BUILDPLATFORM
#ARG BUILDARCH
#ARG TARGETPLATFORM
#ARG TARGETOS
#ARG TARGETARCH
#
#WORKDIR /data/agent
#RUN mkdir /data/agent/node
#COPY --from=whatap_cadvisor_helper_build /data/agent/node/cadvisor_helper ./node
RUN apk add --no-cache bash
RUN apk add --no-cache curl
RUN apk add --no-cache jq
#CMD []